# Versioning System
CITRIC_CODENAME := Slimeade
CITRIC_MAJOR_VERSION := v1.0
CITRIC_RELEASE_VERSION := Alpha
CITRIC_BUILD_TYPE ?= UNOFFICIAL
CITRIC_BUILD_VARIANT := VANILLA

# Gapps
ifeq ($(WITH_GAPPS),true)
CITRIC_BUILD_VARIANT := GAPPS
endif

# CitricOS Release
ifeq ($(CITRIC_BUILD_TYPE), OFFICIAL)
  OFFICIAL_DEVICES = $(shell cat vendor/citric/citric.devices)
  FOUND_DEVICE =  $(filter $(CITRIC_BUILD), $(OFFICIAL_DEVICES))
    ifeq ($(FOUND_DEVICE),$(CITRIC_BUILD))
      CITRIC_BUILD_TYPE := OFFICIAL
    else
      CITRIC_BUILD_TYPE := UNOFFICIAL
      $(error Device is not official "$(CITRIC_BUILD)")
    endif
endif

# System version
TARGET_PRODUCT_SHORT := $(subst citric_,,$(CITRIC_BUILD_TYPE))

CITRIC_DATE_YEAR := $(shell date -u +%Y)
CITRIC_DATE_MONTH := $(shell date -u +%m)
CITRIC_DATE_DAY := $(shell date -u +%d)
CITRIC_DATE_HOUR := $(shell date -u +%H)
CITRIC_DATE_MINUTE := $(shell date -u +%M)

CITRIC_BUILD_DATE := $(CITRIC_DATE_YEAR)$(CITRIC_DATE_MONTH)$(CITRIC_DATE_DAY)-$(CITRIC_DATE_HOUR)$(CITRIC_DATE_MINUTE)
CITRIC_BUILD_VERSION := $(CITRIC_MAJOR_VERSION)-$(CITRIC_RELEASE_VERSION)
CITRIC_BUILD_FINGERPRINT := CitricOS/$(CITRIC_MOD_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CITRIC_BUILD_DATE)
CITRIC_VERSION := CitricOS-$(CITRIC_CODENAME)-$(CITRIC_BUILD_VERSION)-$(CITRIC_BUILD)-$(CITRIC_BUILD_TYPE)-$(CITRIC_BUILD_DATE)
CITRIC_RELEASE := CitricOS-$(CITRIC_CODENAME)-$(CITRIC_BUILD_VERSION)-$(CITRIC_BUILD)-$(CITRIC_BUILD_TYPE)-$(CITRIC_BUILD_VARIANT)-$(CITRIC_BUILD_DATE)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
  ro.citric.device=$(CITRIC_BUILD) \
  ro.citric.version=$(CITRIC_VERSION) \
  ro.citric.build.version=$(CITRIC_BUILD_VERSION) \
  ro.citric.build.type=$(CITRIC_BUILD_TYPE) \
  ro.citric.build.variant=$(CITRIC_BUILD_VARIANT) \
  ro.citric.build.date=$(CITRIC_BUILD_DATE) \
  ro.citric.build.fingerprint=$(CITRIC_BUILD_FINGERPRINT)
